### ISSUE TITLE
[Bug]: Program fails to run when a reminder is created for a set time, every 15 minutes, four times

### ISSUE THREAD

**Issue by IcedQuinn** [dgsasha/remembrance#50] opened 2023-06-08 05:58 UTC
### Package

Flathub

### Distribution

Void

### Describe the bug

Program fails to run when a reminder is created for a set time, every 15 minutes, four times

### To Reproduce

Create a reminder for 8am, set a repeat for every 15 minutes, set recurrence to 8 times. Note the reminder does not appear in the list. And the software will no longer run.

```
icedquinn@astaraline ~ [1]> flatpak run io.github.dgsasha.Remembrance
2023-06-08 00:51:44,553 - remembrance - INFO - application:connect_to_service - Connected to service
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 86, in do_command_line
    self.do_activate()
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 144, in do_activate
    self.win = MainWindow(self.page, self)
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 147, in __init__
    self.unpack_reminders(reminders)
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 601, in unpack_reminders
    self.display_reminder(**reminder)
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 640, in display_reminder
    reminder = Reminder(
  File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 76, in __init__
    self.set_labels()
  File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 268, in set_labels
    self.set_repeat_label()
  File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 254, in set_repeat_label
    self.win.get_repeat_label(
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 272, in get_repeat_label
    type_name = repeat_frequency + ' ' + _('minutes')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by dgsasha** [comment] 2023-06-10 23:16
This is a duplicate of https://github.com/remindersdevs/Reminders/issues/36

This is already fixed, but this app is about to get moved to a new flatpak repository so the fix won't be available until then, sorry :(

**Closed as completed** 2023-06-10 23:17 UTC
Labels: bug

**Comment by dgsasha** [comment] 2023-06-10 23:19
I've been busy with school but I would expect this to happen within the next week or two, the new release is pretty much ready, just need to test some things cause there are a huge amount of changes.
